from sqlalchemy import (
    Column, Integer, Float, String, Boolean, DateTime,
    Text, ForeignKey, JSON
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.database import Base


class Portfolio(Base):
    """Main portfolio account tracking cash balance and NAV."""
    __tablename__ = "portfolios"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), default="Main Portfolio")
    cash = Column(Float, default=1000.0, nullable=False)
    initial_capital = Column(Float, default=1000.0, nullable=False)
    total_value = Column(Float, default=1000.0, nullable=False)
    total_pnl = Column(Float, default=0.0)
    total_pnl_pct = Column(Float, default=0.0)
    peak_value = Column(Float, default=1000.0)
    max_drawdown = Column(Float, default=0.0)
    daily_pnl = Column(Float, default=0.0)
    daily_pnl_start_value = Column(Float, default=1000.0)
    trading_halted = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), server_default=func.now())

    positions = relationship("Position", back_populates="portfolio", cascade="all, delete-orphan")
    trades = relationship("Trade", back_populates="portfolio", cascade="all, delete-orphan")


class Position(Base):
    """Currently open positions in the portfolio."""
    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, index=True)
    portfolio_id = Column(Integer, ForeignKey("portfolios.id"), nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    qty = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    side = Column(String(10), default="long")  # long | short
    strategy = Column(String(50), nullable=True)
    unrealized_pnl = Column(Float, default=0.0)
    unrealized_pnl_pct = Column(Float, default=0.0)
    opened_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), server_default=func.now())

    portfolio = relationship("Portfolio", back_populates="positions")


class Trade(Base):
    """Executed trades ledger (historical record)."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True)
    portfolio_id = Column(Integer, ForeignKey("portfolios.id"), nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    side = Column(String(10), nullable=False)  # buy | sell
    qty = Column(Float, nullable=False)
    price = Column(Float, nullable=False)
    order_type = Column(String(20), default="market")  # market | limit | stop
    status = Column(String(20), default="filled")  # filled | rejected | cancelled | pending
    pnl = Column(Float, default=0.0)
    pnl_pct = Column(Float, default=0.0)
    strategy = Column(String(50), nullable=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)
    commission = Column(Float, default=0.0)
    slippage = Column(Float, default=0.0)
    broker_order_id = Column(String(100), nullable=True)
    executed_at = Column(DateTime(timezone=True), server_default=func.now())

    portfolio = relationship("Portfolio", back_populates="trades")
    signal = relationship("Signal", back_populates="trades")


class Signal(Base):
    """Trading signals generated by strategies and AI engine."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    action = Column(String(10), nullable=False)  # buy | sell | hold
    strategy = Column(String(50), nullable=False)
    confidence = Column(Float, nullable=True)  # 0.0 - 1.0
    price_at_signal = Column(Float, nullable=False)
    indicators = Column(JSON, nullable=True)  # snapshot of indicator values
    ai_prediction = Column(String(10), nullable=True)  # UP | DOWN | NEUTRAL
    ai_confidence = Column(Float, nullable=True)
    executed = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    trades = relationship("Trade", back_populates="signal")
    predictions = relationship("AIPrediction", back_populates="signal")


class AIPrediction(Base):
    """Log of AI model predictions for tracking accuracy."""
    __tablename__ = "ai_predictions"

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)
    symbol = Column(String(20), nullable=False, index=True)
    model_type = Column(String(50), default="xgboost")
    predicted_direction = Column(String(10), nullable=False)  # UP | DOWN
    confidence = Column(Float, nullable=False)
    features = Column(JSON, nullable=True)
    actual_direction = Column(String(10), nullable=True)  # filled after the fact
    was_correct = Column(Boolean, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    signal = relationship("Signal", back_populates="predictions")


class HistoricalPrice(Base):
    """Cached OHLCV bar data."""
    __tablename__ = "historical_prices"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(10), default="1d")  # 1m | 5m | 15m | 1h | 1d
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)


class Strategy(Base):
    """Strategy configuration and parameter storage."""
    __tablename__ = "strategies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)
    enabled = Column(Boolean, default=True)
    weight = Column(Float, default=1.0)
    params = Column(JSON, default={})
    description = Column(Text, nullable=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), server_default=func.now())


class RiskLog(Base):
    """Log of risk management decisions and limit violations."""
    __tablename__ = "risk_logs"

    id = Column(Integer, primary_key=True, index=True)
    event_type = Column(String(50), nullable=False)  # max_loss_hit | position_rejected | halt | etc
    symbol = Column(String(20), nullable=True)
    detail = Column(Text, nullable=True)
    portfolio_value = Column(Float, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class EquitySnapshot(Base):
    """Time-series snapshots of portfolio value for equity curve plotting."""
    __tablename__ = "equity_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    portfolio_id = Column(Integer, ForeignKey("portfolios.id"), nullable=False)
    total_value = Column(Float, nullable=False)
    cash = Column(Float, nullable=False)
    positions_value = Column(Float, nullable=False)
    daily_pnl = Column(Float, default=0.0)
    recorded_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
